### PR TITLE
Set the array length explicitly

### LINKED ISSUE #41: FlattenIntoArray does not set length?
Step 3.c.v.2 creates the data property for the index, but does not update the `length` property - certainly native Array `[[DefineOwnProperty]]` updates it for you (https://tc39.github.io/ecma262/#sec-array-exotic-objects-defineownproperty-p-desc step 3.h.ii) - but whatever's created with the species constructor may not.

Precedent is to manually set it:
 - https://tc39.github.io/ecma262/#sec-array-len step 8
 - https://tc39.github.io/ecma262/#sec-array.from step 5.e.iv.1
 - https://tc39.github.io/ecma262/#sec-array.of step 8
 - https://tc39.github.io/ecma262/#sec-array.prototype.concat step 6
 - https://tc39.github.io/ecma262/#sec-array.prototype.pop step 3.a & step 4.e
 - https://tc39.github.io/ecma262/#sec-array.prototype.push step 7
 - https://tc39.github.io/ecma262/#sec-array.prototype.shift step 3.a & step 8
 - https://tc39.github.io/ecma262/#sec-array.prototype.slice step 11
 - https://tc39.github.io/ecma262/#sec-array.prototype.splice step 12 & step 19
 - https://tc39.github.io/ecma262/#sec-array.prototype.unshift step 5
 - https://tc39.github.io/ecma262/#sec-arraycreate step 10

I think you'd want to add it as 3.c.v.3?

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #41

### CODE REVIEW

**Comment by michaelficarra** [comment]
This adds an observable `Set` operation for each recursive call of `FlattenIntoArray`. I don't think that's what we want. We only want one `Set` operation on the `length` property after the work has been completed.

**Comment by ljharb** [comment]
That'd be ideal; but 1) that's not how any of the existing examples in the spec do it, 2) if the TypeError exception gets thrown, the length wouldn't get set at all, 3) array subclasses might do a bunch of weird stuff when the length is set, and that'd be expected to happen when each item is added.

It also wouldn't be observable on an unmodified `Array.prototype` with a native array being the `target`, which I assume is how implementations optimize all the other spec operations.

**Comment by michaelficarra** [comment]
@ljharb That's not how, for example, [`Array.prototype.push` works](https://tc39.github.io/ecma262/#sec-array.prototype.push). It only sets the length once. Also, it's not just an unmodified `Array.prototype`, but also `Object.prototype`.

**Comment by ljharb** [comment]
Agreed on the unmodified prototypes for sure.

That's a fair point, given that, I'll set it once at the end instead.

**Comment by ljharb** [comment]
Should the Set be outside of `FlattenIntoArray` then, since it's recursive? iow, repeated in both flatten and flatMap?

**Comment by michaelficarra** [comment]
Yeah, I think so.

**Comment by ljharb** [comment]
Updated.

**Pull request merged**
